linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - gosec
    - bodyclose
    - contextcheck
    - noctx

linters-settings:
  gosec:
    excludes:
      - G115

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-rules:
    - path: internal/db/generated/
      linters:
        - errcheck
        - gosec
        - staticcheck
        - unused
    - path: internal/handler/types.go
      linters:
        - unused
